server {
    server_name dolina.elifsyndicate.online www.dolina.elifsyndicate.online;

    include /etc/nginx/snippets/acme-challenge.conf;

    if ($host = www.dolina.elifsyndicate.online) {
        return 301 https://dolina.elifsyndicate.online$request_uri;
    }

    location / {
        proxy_pass http://127.0.0.1:13010;
        include /etc/nginx/snippets/proxy_nextjs.conf;
    }

    location /_next/static/ {
        proxy_pass http://127.0.0.1:13010;
        include /etc/nginx/snippets/proxy_nextjs.conf;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/dolina.elifsyndicate.online/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/dolina.elifsyndicate.online/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    listen 80;
    listen [::]:80;
    server_name dolina.elifsyndicate.online www.dolina.elifsyndicate.online;

    include /etc/nginx/snippets/acme-challenge.conf;

    if ($host = www.dolina.elifsyndicate.online) {
        return 301 http://dolina.elifsyndicate.online$request_uri;
    }

    return 301 https://dolina.elifsyndicate.online$request_uri;
}
